language: ruby
rvm:
  - "2.0"
  - "2.1.10"
  - "2.2.10"
  - "2.3.8"
  - "2.4.5"
  - "2.5.3"
  - "2.6.0"
  - "2.7.0"
  - ruby-head
  - jruby-head
sudo: false
cache: bundler
after_script: bundle exec codeclimate-test-reporter
matrix:
  allow_failures:
    - rvm: "2.6.0"
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
